name: Dupe
version: ${version}
main: me.gregzee.dupe.Dupe
api-version: '1.20.4'
authors: [ Gregzee ]
description: Your plugin description here.
load: POSTWORLD
depend: [CommandAPI]

commands:
  dupe:
    aliases:
      - d
  dupem:
    usage: /<command> <reload>